// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWtXxO6GxMzEiGBmjXplW-jHCxIsXLLDU',
    appId: '1:500783283661:web:f013d669e5a697e9a35884',
    messagingSenderId: '500783283661',
    projectId: 'layoverdating-app',
    authDomain: 'layoverdating-app.firebaseapp.com',
    storageBucket: 'layoverdating-app.appspot.com',
    measurementId: 'G-H592YFPYTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjph6bx3QvOnHRhrgqNSEd8qekUOev5K0',
    appId: '1:500783283661:android:e5c1c689cf3909c3a35884',
    messagingSenderId: '500783283661',
    projectId: 'layoverdating-app',
    storageBucket: 'layoverdating-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOlE8mppnnPMm_8nCOnfGLWugDicx2NMw',
    appId: '1:500783283661:ios:98b98e256f7791f2a35884',
    messagingSenderId: '500783283661',
    projectId: 'layoverdating-app',
    storageBucket: 'layoverdating-app.appspot.com',
    iosClientId: '500783283661-f7hpuhtr8b0f28g3a9g51ekl12k0ilc5.apps.googleusercontent.com',
    iosBundleId: 'com.layoverdating.layover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOlE8mppnnPMm_8nCOnfGLWugDicx2NMw',
    appId: '1:500783283661:ios:98b98e256f7791f2a35884',
    messagingSenderId: '500783283661',
    projectId: 'layoverdating-app',
    storageBucket: 'layoverdating-app.appspot.com',
    iosClientId: '500783283661-f7hpuhtr8b0f28g3a9g51ekl12k0ilc5.apps.googleusercontent.com',
    iosBundleId: 'com.layoverdating.layover',
  );
}
